name: cobo_flutter_template
description: "Cobo ucw example app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  http: 1.2.2
  logging: 1.3.0
  rxdart: 0.28.0
  shared_preferences: 2.3.2
  json_annotation: 4.9.0
  # ui design
  tdesign_flutter: 0.1.7
  url_launcher: ^6.2.4
  # Cobo ucw sdk
  ucw_sdk:
    git:
      url: https://github.com/CoboGlobal/cobo-ucw-sdk-flutter.git
      ref: ca173084394737c8945917bf6d0be47e9f5acc73  
  path_provider: ^2.1.5
  frontend_server_client: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The "flutter_lints" encourage good coding practices
  flutter_lints: 5.0.0

  # Code generator
  build_runner: 2.4.13
  json_serializable: 6.8.0  # Json model generator

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # i18n
  generate: true # Add this line
